/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Color;

/**
 *
 * @author Viktorija
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    private boolean stateBtnBlue = true;
    private boolean stateBtnRed = true;
    private boolean stateBtnGreen = true;

    public Menu() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRed = new javax.swing.JButton();
        btnGreen = new javax.swing.JButton();
        btnBlue = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        txtIevade = new javax.swing.JTextField();
        btnForText = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRed.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        btnRed.setText("Sarkans");
        btnRed.setActionCommand("btnred");
        btnRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRedActionPerformed(evt);
            }
        });

        btnGreen.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        btnGreen.setText("Zaļš");
        btnGreen.setToolTipText("");
        btnGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGreenActionPerformed(evt);
            }
        });

        btnBlue.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        btnBlue.setText("Zils");
        btnBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBlueActionPerformed(evt);
            }
        });

        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnForText.setText("OK");
        btnForText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnNew, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnRed, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGreen, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnBlue, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(txtIevade, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnForText)))
                .addContainerGap(187, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRed, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(btnBlue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGreen, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnForText)
                    .addComponent(txtIevade))
                .addContainerGap(139, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBlueActionPerformed
        if (stateBtnBlue) {
            btnBlue.setBackground(Color.blue);
            btnBlue.setForeground(Color.black);

        } else {

            btnBlue.setBackground(Color.gray);
            btnBlue.setForeground(Color.yellow);
        }
        stateBtnBlue = !stateBtnBlue;
        changeColour();

    }//GEN-LAST:event_btnBlueActionPerformed

    private void btnRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedActionPerformed
        if (stateBtnRed) {
            btnRed.setBackground(Color.red);
            btnRed.setForeground(Color.black);
        } else {
            btnRed.setBackground(Color.GRAY);
            btnRed.setForeground(Color.YELLOW);
        }

        stateBtnRed = !stateBtnRed;
        changeColour();


    }//GEN-LAST:event_btnRedActionPerformed

    private void btnGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGreenActionPerformed
        if (stateBtnGreen) {
            btnGreen.setBackground(Color.green);
            btnGreen.setForeground(Color.black);
        } else {
            btnGreen.setBackground(Color.gray);
            btnGreen.setForeground(Color.yellow);
        }
        stateBtnGreen = !stateBtnGreen;
        changeColour();

    }//GEN-LAST:event_btnGreenActionPerformed

    private void btnForTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForTextActionPerformed
        int a = Integer.parseInt(txtIevade.getText());

        switch (a) {
            case 1:
                btnNew.setBackground(Color.red);
                break;
            case 2:
                btnNew.setBackground(Color.green);
                break;
            case 3:
                btnNew.setBackground(Color.blue);
                break;
            case 4:
                btnNew.setBackground(Color.yellow);
                break;
            case 5:
                btnNew.setBackground(Color.cyan);
                break;
            case 6:
                btnNew.setBackground(Color.magenta);
                break;
            case 7:
                btnNew.setBackground(Color.white);
                break;
            case 8:
                btnNew.setBackground(Color.gray);
                break;
            default:
                btnNew.setBackground(Color.gray);
        }

    }//GEN-LAST:event_btnForTextActionPerformed


    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        btnRed.setBackground(Color.gray);
        stateBtnRed = true;

        btnGreen.setBackground(Color.gray);
        stateBtnGreen = true;

        btnBlue.setBackground(Color.gray);
        stateBtnBlue = true;

        btnNew.setBackground(Color.gray);
    }//GEN-LAST:event_btnNewActionPerformed

    private void changeColour() {
        if (!stateBtnGreen && !stateBtnRed && stateBtnBlue) {
            btnNew.setBackground(Color.yellow);
        }

        if (!stateBtnGreen && !stateBtnBlue && stateBtnRed) {
            btnNew.setBackground(Color.cyan);
        }
        if (!stateBtnRed && !stateBtnBlue && stateBtnGreen) {
            btnNew.setBackground(Color.magenta);
        }

        if (!stateBtnRed && !stateBtnGreen && !stateBtnBlue) {
            btnNew.setBackground(Color.white);
        }

        if (stateBtnRed && stateBtnGreen && stateBtnBlue) {
            btnNew.setBackground(Color.gray);
        }

        if (stateBtnGreen && stateBtnRed && !stateBtnBlue) {
            btnNew.setBackground(Color.blue);
        }

        if (stateBtnGreen && !stateBtnRed && stateBtnBlue) {
            btnNew.setBackground(Color.red);
        }
        if (!stateBtnGreen && stateBtnRed && stateBtnBlue) {
            btnNew.setBackground(Color.green);
        }
        differentMixStateChange();
    }

    private void differentMixStateChange() {
        String result = String.valueOf(stateBtnRed) + String.valueOf(stateBtnGreen) + 
                String.valueOf(stateBtnBlue); 
        System.out.println(result);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);

            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBlue;
    private javax.swing.JButton btnForText;
    private javax.swing.JButton btnGreen;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnRed;
    private javax.swing.JTextField txtIevade;
    // End of variables declaration//GEN-END:variables

}
